# Generated by Django 4.2.13 on 2024-07-06 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_toolshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rental_time', models.IntegerField()),
                ('rental_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.rentalcart')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.toolsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='rentalcart',
            name='tools',
            field=models.ManyToManyField(through='payment.RentalCartItem', to='api.toolsmodel'),
        ),
        migrations.AddField(
            model_name='rentalcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
