# Generated by Django 4.2.13 on 2024-07-20 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCart',
            fields=[
                ('rental_cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('rental_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('open', 'Open'), ('cancelled', 'Cancelled')], default='open', max_length=50)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_completed', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrderItem',
            fields=[
                ('rental_order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_rented', models.IntegerField()),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.rentalorder')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tools')),
            ],
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='tools',
            field=models.ManyToManyField(through='payment.RentalOrderItem', to='api.tools'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RentalCartItem',
            fields=[
                ('rental_cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('rental_time', models.IntegerField()),
                ('rental_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.rentalcart')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.toolsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='rentalcart',
            name='tools',
            field=models.ManyToManyField(through='payment.RentalCartItem', to='api.toolsmodel'),
        ),
        migrations.AddField(
            model_name='rentalcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
