# Generated by Django 4.2.13 on 2024-07-13 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_toolshistory'),
        ('payment', '0002_rentalcart_date_created_rentalcart_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('open', 'Open'), ('cancelled', 'Cancelled')], default='open', max_length=50)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_completed', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_rented', models.IntegerField()),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.rentalorder')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tools')),
            ],
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='tools',
            field=models.ManyToManyField(through='payment.RentalOrderItem', to='api.tools'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
