# Generated by Django 4.2.13 on 2024-07-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolshistory',
            name='rental_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.rentalorder'),
            preserve_default=False,
        ),
    ]
