# Generated by Django 4.2.13 on 2024-06-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tools_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='price',
        ),
        migrations.AddField(
            model_name='toolsmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='toolsmodel',
            name='image_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='toolsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tools',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
