# Generated by Django 4.2.13 on 2024-06-18 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tools_description_remove_tools_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='category',
        ),
        migrations.AddField(
            model_name='toolsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.toolscategory'),
        ),
        migrations.AlterUniqueTogether(
            name='toolsmodel',
            unique_together={('brand', 'model')},
        ),
    ]
