# Generated by Django 4.2.13 on 2024-07-21 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_toolshistory_rental_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotUserHistory',
            fields=[
                ('bot_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.JSONField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
