# Generated by Django 4.2.13 on 2024-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatbotuserhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotuserhistory',
            old_name='history',
            new_name='chat_history',
        ),
        migrations.AddField(
            model_name='chatbotuserhistory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
