# Generated by Django 4.2.13 on 2024-06-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tools_category_toolsmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsmodel',
            name='name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
