# Generated by Django 4.2.13 on 2024-06-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_toolsmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='image_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
