# Generated by Django 4.2.13 on 2024-07-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_toolshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolshistory',
            name='rent_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='toolshistory',
            name='rent_start_date',
            field=models.DateTimeField(),
        ),
    ]
